version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '4000:5432'
    volumes:
      - .db-data:/var/lib/postgres/data
    tty: true